[discord]
# Your Disocrd auth token
# Env: DISCORD_AUTH_TOKEN
authToken = ""
# Prefix (and optional postfix) to use for Math messages
# If no postfix is provided, prefix can be used instead
prefix = "$$"
postfix = '$$'

[discord.status]
# Statuses that will be rotated through as the bot's "Playing" activity
list = [
  "with LaTeX",
]
# How long to keep each status up for, in seconds
duration = 60
